spring:

  application:
    name: api_rest_java_with_spring_boot  

  datasource:
    url: jdbc:postgresql://localhost:5432/api_rest_java_with_spring_boot?currentSchema=public&stringtype=unspecified&options=-c%20timezone%3DUTC
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      "[hibernate.jdbc.time_zone]": UTC
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  jackson:
      time-zone: UTC
