spring:
  application:
    name: api_rest_java_with_spring_boot

  datasource:
    url: jdbc:postgresql://localhost:5432/api_rest_java_with_spring_boot?currentSchema=public&stringtype=unspecified&options=-c%20timezone%3DAmerica/Sao_Paulo
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      "[hibernate.jdbc.time_zone]": America/Sao_Paulo
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  jackson:
      time-zone: America/Sao_Paulo
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true